"""initial

Revision ID: 173e03fba43b
Revises: 40558ba1ce27
Create Date: 2025-05-01 20:35:54.104460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '173e03fba43b'
down_revision: Union[str, None] = '40558ba1ce27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flowers_id'), 'flowers', ['id'], unique=False)
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'password')
    op.drop_index(op.f('ix_flowers_id'), table_name='flowers')
    # ### end Alembic commands ###
