"""add status to project

Revision ID: 5dd9bee9f743
Revises: db0d0496c45f
Create Date: 2025-06-03 22:41:49.997808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd9bee9f743'
down_revision: Union[str, None] = 'db0d0496c45f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_project', 'role',
               existing_type=postgresql.ENUM('OWNER', 'MEMBER', name='roleenum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_project', 'role',
               existing_type=postgresql.ENUM('OWNER', 'MEMBER', name='roleenum'),
               nullable=True)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('projects', 'status')
    # ### end Alembic commands ###
